### ISSUE TITLE
Any Preview?

### ISSUE THREAD

**Issue by oschakravarthi** [jlwitthuhn/cycles-shader-editor#2]
Hi, Is there any preview while defining the shader graph?

**Comment by jlwitthuhn** [comment]
Hey, sorry to take so long to respond.

Right now that isn't possible because this editor doesn't actually embed Cycles, so it isn't capable of doing any preview render.

It may in the future, but that would be a very big change that I don't expect I'll be able to make any time soon.

For now the only way to see your shader is to save and then press the "update preview" button inside Max. I'm looking into making that update happen automatically when you save.

**Comment by jlwitthuhn** [comment]
Closing this issue as I'm not working on this version of the editor anymore. See the readme for details.
